/** The one semantic authority for the reviewed Surface family. */
export type CanonicalReviewedSurfaceContract = {
  surfaceId: string
  wrapper: string
  outerRegexScriptId: string
  helperRegexScriptIds: string[]
  imageTargets: string[]
  defaultHybridOwner: 'relay' | 'regex'
  sampleXml: string
  utilityPrompt: string
}

const image = (id: string, target: string, slot: string, aspect: string, alt: string) => `<image_request id="${id}" target="${target}" slot="${slot}" aspect="${aspect}" alt="${alt}"><scene_brief>Scene-specific visual content.</scene_brief></image_request>`
const reviewed = (contract: Omit<CanonicalReviewedSurfaceContract, 'utilityPrompt'> & { rules: string }) => ({ ...contract, utilityPrompt: `REVIEWED ${contract.surfaceId.toUpperCase()} — CANONICAL XML\n${contract.rules}\nEmit only this canonical grammar for new content. Relay and Regex consume the same XML.\n\nCONTRACT EXAMPLE\n${contract.sampleXml}` })

export const CANONICAL_REVIEWED_SURFACE_CONTRACTS: CanonicalReviewedSurfaceContract[] = [
  reviewed({ surfaceId: 'email-thread', wrapper: 'email_thread', outerRegexScriptId: 'surface_review_email', helperRegexScriptIds: ['surface_review_v2_xform_email_item'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <email_thread account="…" time="…">. Each <email_item slot="1-5" from="…" subject="…" preview="…" time="…"> contains <email_body> and optional <email_attachment filename="…">media</email_attachment>. Never use email_inbox or em_message.', sampleXml: `<email_thread account="Mailbox" time="08:30"><email_item slot="1" from="Sender" subject="Subject" preview="Preview" time="08:20"><email_body>Readable body.</email_body><email_attachment filename="attachment.png">${image('email-attachment-1', 'custom.artifact-media', 'email-attachment-1', '16:9', 'Email attachment')}</email_attachment></email_item></email_thread>` }),
  reviewed({ surfaceId: 'newspaper', wrapper: 'newspaper', outerRegexScriptId: 'surface_review_newspaper', helperRegexScriptIds: [], imageTargets: [], defaultHybridOwner: 'regex', rules: 'Use <newspaper name="…" date="…" headline="…" subhead="…">article content</newspaper>; all four root attributes are required.', sampleXml: '<newspaper name="Publication" date="Today" headline="Headline" subhead="Readable subhead">Concise editorial copy.</newspaper>' }),
  reviewed({ surfaceId: 'inline-chat', wrapper: 'inline_chat', outerRegexScriptId: 'surface_review_inline_chat', helperRegexScriptIds: ['surface_review_v2_xform_message', 'surface_review_v3_xform_avatar_message', 'surface_review_v2_xform_message_media'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <inline_chat header="…" time="…"> with chat_msg, avatar_msg, and chat_media helper seams. Never use generic message.', sampleXml: `<inline_chat header="Conversation" time="08:30"><chat_msg side="left" user="Person" avatar="P">Message.</chat_msg><avatar_msg side="right" user="Other"><avatar>A</avatar><text>Reply.</text></avatar_msg><chat_media side="left">${image('chat-media-1', 'custom.artifact-media', 'chat-media-1', '16:9', 'Chat attachment')}</chat_media></inline_chat>` }),
  reviewed({ surfaceId: 'dating-profile', wrapper: 'tinder', outerRegexScriptId: 'surface_review_tinder', helperRegexScriptIds: ['surface_review_tinder_user_seam', 'surface_review_tinder_profile_seam'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <tinder> with one <user><name/><avatar/></user> and <profiles> containing exactly three <profile slot="…" prev="…" next="…"> blocks. Child order is name, age, subtitle, role, tags, bio, photo. Never emit dating_profile or profile id/name/age attributes.', sampleXml: `<tinder><user><name>Viewer</name><avatar>${image('tinder-user-1', 'custom.artifact-media', 'tinder-user-1', '1:1', 'User avatar')}</avatar></user><profiles><profile slot="1" prev="3" next="2"><name>Profile One</name><age>28</age><subtitle>Nearby</subtitle><role>Artist</role><tags>music · books</tags><bio>Short bio.</bio><photo>${image('tinder-profile-1', 'custom.artifact-media', 'tinder-profile-1', '3:4', 'Dating portrait')}</photo></profile><profile slot="2" prev="1" next="3"><name>Profile Two</name><age>29</age><subtitle>Nearby</subtitle><role>Designer</role><tags>film · walks</tags><bio>Short bio.</bio><photo>${image('tinder-profile-2', 'custom.artifact-media', 'tinder-profile-2', '3:4', 'Dating portrait')}</photo></profile><profile slot="3" prev="2" next="1"><name>Profile Three</name><age>30</age><subtitle>Nearby</subtitle><role>Writer</role><tags>tea · art</tags><bio>Short bio.</bio><photo>${image('tinder-profile-3', 'custom.artifact-media', 'tinder-profile-3', '3:4', 'Dating portrait')}</photo></profile></profiles></tinder>` }),
  reviewed({ surfaceId: 'livestream', wrapper: 'livestream', outerRegexScriptId: 'surface_review_twitch', helperRegexScriptIds: ['surface_review_v2_xform_live_msg', 'surface_review_v2_xform_live_donation', 'surface_review_v2_xform_live_poll', 'surface_review_v2_xform_live_mod'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <livestream>, never twitch_stream. Use live_media, live_chat with live_msg/live_donation/live_poll, and live_mods with live_mod.', sampleXml: `<livestream title="Live title" channel="Channel" viewers="2.4K" category="Category" status="LIVE"><live_media>${image('live-frame-1', 'custom.artifact-media', 'live-frame-1', '16:9', 'Live frame')}</live_media><live_chat><live_msg user="Viewer" avatar="V">Message.</live_msg><live_donation user="Supporter" amount="$5">Thanks.</live_donation><live_poll question="Question?"><poll_option>Yes</poll_option><poll_option>No</poll_option></live_poll></live_chat><live_mods><live_mod user="Mod" role="Moderator" avatar="M"/></live_mods></livestream>` }),
  reviewed({ surfaceId: 'instagram-dm', wrapper: 'instagram_dm', outerRegexScriptId: 'surface_review_instagram_dm', helperRegexScriptIds: ['surface_review_v2_xform_message', 'surface_review_v3_xform_avatar_message', 'surface_review_v2_xform_message_media'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <instagram_dm name="…" handle="…" time="…"> with dm_msg, avatar_msg, and dm_media helper seams.', sampleXml: `<instagram_dm name="Person" handle="@person" time="08:30"><avatar_msg side="left" user="Person"><avatar>A</avatar><text>Message.</text></avatar_msg><dm_msg side="right" user="You" avatar="Y">Reply.</dm_msg><dm_media side="left">${image('instagram-media-1', 'custom.artifact-media', 'instagram-media-1', '4:5', 'DM attachment')}</dm_media></instagram_dm>` }),
  reviewed({ surfaceId: 'x-dm', wrapper: 'x_dm', outerRegexScriptId: 'surface_review_x_dm', helperRegexScriptIds: ['surface_review_v2_xform_message', 'surface_review_v3_xform_avatar_message', 'surface_review_v2_xform_message_media'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <x_dm name="…" handle="…" time="…"> with dm_msg, avatar_msg, and dm_media helper seams. Do not teach twitter_dm.', sampleXml: '<x_dm name="Person" handle="@person" time="08:30"><dm_msg side="left" user="Person" avatar="P">Message.</dm_msg></x_dm>' }),
  reviewed({ surfaceId: 'discord-dm', wrapper: 'discord_dm', outerRegexScriptId: 'surface_review_discord_dm', helperRegexScriptIds: ['surface_review_v2_xform_discord_msg', 'surface_review_v3_xform_discord_avatar_message', 'surface_review_v2_xform_message_media'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <discord_dm name="…" status="…" time="…"> with discord_msg or discord_avatar_msg helper seams.', sampleXml: '<discord_dm name="Person" status="Online" time="08:30"><discord_avatar_msg user="Person" time="08:30"><avatar>A</avatar><text>Message.</text></discord_avatar_msg><discord_msg user="Other" avatar="O" time="08:31">Reply.</discord_msg></discord_dm>' }),
  reviewed({ surfaceId: 'discord-server', wrapper: 'discord_server', outerRegexScriptId: 'surface_review_discord_server', helperRegexScriptIds: ['reverie_relay_c4_xform_server_msg_avatar', 'surface_review_v2_xform_discord_msg', 'surface_review_v3_xform_server_avatar_message', 'surface_review_v2_xform_discord_media', 'surface_review_v2_xform_discord_channel'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <discord_server server="…" topic="…" members="…" online="…">; members and online are optional for legacy messages but populate them for new Surfaces. Write exactly four server_channel siblings with slot/name/description. Recurring participants, including the local participant when identity detail is sufficient, use server_avatar_msg with one reusable 1:1 image_request; repeat the same stable id and slot for that participant, never a second avatar request. Use server_msg only when sufficient visual identity information does not exist. Never emit users/channels/channel/message.', sampleXml: `<discord_server server="Server" topic="Topic" members="1,284" online="318"><server_channel slot="1" name="general" description="General chat"><server_avatar_msg user="Guide" time="08:30"><avatar>${image('discord-server-avatar-guide', 'custom.artifact-media', 'discord-server-avatar-guide', '1:1', 'Avatar of Guide')}</avatar><text>Message.</text></server_avatar_msg><server_avatar_msg user="Local" time="08:31"><avatar>${image('discord-server-avatar-local', 'custom.artifact-media', 'discord-server-avatar-local', '1:1', 'Avatar of Local')}</avatar><text>Reply.</text></server_avatar_msg><server_media>${image('server-media-1', 'custom.artifact-media', 'server-media-1', '16:9', 'Server attachment')}</server_media></server_channel><server_channel slot="2" name="art-share" description="Visual work"><server_avatar_msg user="Guide" time="08:32"><avatar>${image('discord-server-avatar-guide', 'custom.artifact-media', 'discord-server-avatar-guide', '1:1', 'Avatar of Guide')}</avatar><text>Shared update.</text></server_avatar_msg></server_channel><server_channel slot="3" name="spoiler-zone" description="Private discussion"><server_avatar_msg user="Local" time="08:33"><avatar>${image('discord-server-avatar-local', 'custom.artifact-media', 'discord-server-avatar-local', '1:1', 'Avatar of Local')}</avatar><text>Reply.</text></server_avatar_msg></server_channel><server_channel slot="4" name="off-topic" description="Casual conversation"><server_avatar_msg user="Guide" time="08:34"><avatar>${image('discord-server-avatar-guide', 'custom.artifact-media', 'discord-server-avatar-guide', '1:1', 'Avatar of Guide')}</avatar><text>See you there.</text></server_avatar_msg></server_channel></discord_server>` }),
  reviewed({ surfaceId: 'google-images', wrapper: 'google_image_search', outerRegexScriptId: 'surface_review_google_images', helperRegexScriptIds: ['surface_review_v2_xform_google_result'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <google_image_search query="…"> and gis_result slot/title/source. Never use result index or gallery_item.', sampleXml: `<google_image_search query="Search phrase"><gis_result slot="1" title="Result" source="Source">${image('google-result-1', 'custom.artifact-media', 'google-result-1', '4:3', 'Search result')}</gis_result></google_image_search>` }),
  reviewed({ surfaceId: 'phone-gallery', wrapper: 'phone_gallery', outerRegexScriptId: 'surface_review_phone_gallery', helperRegexScriptIds: ['surface_review_v2_xform_gallery_item'], imageTargets: ['custom.artifact-media'], defaultHybridOwner: 'regex', rules: 'Use <phone_gallery album="…" time="…"> and gallery_item slot/title/time/location/size. Every saved moment uses its own 1:1 image_request with a square-safe composition and the focal subject inside the central 70%. Grid thumbnails may fill their cells; the enlarged state preserves the full image. Never use photo id/caption.', sampleXml: `<phone_gallery album="Camera" time="08:30"><gallery_item slot="1" title="Photo" time="08:25" location="Place" size="2 MB">${image('gallery-photo-1', 'custom.artifact-media', 'gallery-photo-1', '1:1', 'Gallery photo')}</gallery_item></phone_gallery>` }),
  reviewed({ surfaceId: 'naver-article', wrapper: 'naver_news', outerRegexScriptId: 'interactive_v3_15_naver', helperRegexScriptIds: ['reverie_relay_c4_xform_naver_comment'], imageTargets: ['custom.naver-article'], defaultHybridOwner: 'regex', rules: 'Use <naver_news category="…" headline="…" source="…" byline="…" timestamp="…" comments="…">. Keep article media only in nv_media, followed once by nv_body and then nv_comments. nv_comments is a list of distinct sibling nv_comment elements, never flattened prose: every comment MUST have non-empty user and time attributes and its body is only the element text. Emit exactly the requested comment count; never repeat nv_body or article prose inside nv_comments.', sampleXml: `<naver_news category="Local" headline="Article headline" source="News Desk" byline="Reporter" timestamp="2026.08.18 08:30" comments="3"><nv_media>${image('naver-media-1', 'custom.naver-article', 'naver-media-1', '16:9', 'Article hero')}</nv_media><nv_body>Article copy.</nv_body><nv_comments><nv_comment user="Citizen_77" time="10m ago">Comment one.</nv_comment><nv_comment user="Archivist_K" time="25m ago">Comment two.</nv_comment><nv_comment user="NightOwl" time="1h ago">Comment three.</nv_comment></nv_comments></naver_news>` }),
]

export const CANONICAL_REVIEWED_SURFACE_BY_ID = new Map(CANONICAL_REVIEWED_SURFACE_CONTRACTS.map(contract => [contract.surfaceId, contract]))
export const CANONICAL_REVIEWED_SURFACE_BY_WRAPPER = new Map(CANONICAL_REVIEWED_SURFACE_CONTRACTS.map(contract => [contract.wrapper, contract]))
export const CANONICAL_REVIEWED_SURFACE_PROMPT_MODULES: Record<string, string> = Object.fromEntries(CANONICAL_REVIEWED_SURFACE_CONTRACTS.map(contract => [contract.surfaceId, contract.utilityPrompt]))
