/** User-facing summaries only. These never alter the authoritative Utility contracts. */
export const SURFACE_UTILITY_OVERVIEWS: Readonly<Record<string, string>> = {
  'forum-thread': 'A structured discussion board with separate posts, replies, authors, timestamps, and owned attachments.',
  'email-thread': 'An email client view that preserves each message, sender, subject, time, body, and attachment.',
  'imessage-chat': 'A phone-message conversation with ordered sent/received bubbles and message-owned photos.',
  'workspace-chat': 'A team workspace conversation with channels, named participants, messages, files, and media.',
  livestream: 'A live broadcast frame with an ordered chat feed and moderation information.',
  'dating-profile': 'A swipe-style dating profile with three identity-consistent portrait slots and profile details.',
  'public-bulletin': 'An official public notice with urgency, location, instructions, and documentary media.',
  'case-file': 'A tabbed investigative dossier for people, evidence, notes, and a readable timeline.',
  'relationship-map': 'A visual relationship board connecting named characters with labeled bonds and insights.',
  'instagram-dm': 'An Instagram-style private conversation with individual bubbles and attached media.',
  'x-dm': 'An X-style private message thread with sender direction, timestamps, and attachments.',
  'discord-dm': 'A Discord direct-message exchange with participant identity, ordered messages, and files.',
  'discord-server': 'A multi-channel Discord server view with members, messages, reusable avatars, and media.',
  'google-images': 'A search-results grid whose independent image cards match the authored query.',
  'phone-gallery': 'A noncropping phone photo gallery with square thumbnails and full-image viewing.',
  'tiktok-post': 'A vertical short-video post with caption, engagement, comments, and a 9:16 media slot.',
  'naver-article': 'A Naver-style news article with editorial hero media, article body, and separate comments.',
  newspaper: 'A newspaper article layout with publication hierarchy, headline, body, and editorial image.',
  'inline-chat': 'A compact in-story chat exchange that keeps every message and side visually distinct.',
  'evidence-photo': 'A documented evidence photograph with case metadata, source, caption, and investigator note.',
  smartphone: 'A complete smartphone conversation with ordered text and direction-aware image messages.',
  instagram: 'An Instagram post or carousel with account details, caption, likes, and nested comments.',
  twitter: 'An X timeline post with metrics, optional media, comments, threads, and trends.',
  kakao: 'A KakaoTalk group or private chat with participants, independent bubbles, system rows, and images.',
  'album-cover': 'A square release-art card with title, artist, release type, and context-specific cover art.',
  'magazine-cover': 'An editorial magazine cover with masthead hierarchy and portrait-oriented cover art.',
  'photo-booth-strip': 'Four coordinated vertical photo-booth frames from one identity-consistent session.',
  polaroid: 'A single instant photograph with date, location, and handwritten-style caption.',
  'youtube-thumbnail': 'A YouTube watch-page card with channel metadata, video frame, and separate comments.',
  'character-profile': 'A compact Cast Sheet with a persistent portrait, name, role, hook, and trait.',
  'music-player': 'A music-player card with track metadata, square cover art, lyrics, and queue details.',
  'location-share': 'A context-dependent live route card with destination, ETA, map, note, and waypoints.',
  'voice-memo': 'A playable voice-note card with reusable sender avatar, transcript, duration, and call history.',
  'notes-app': 'A notes application view with a folder, owner, and independently readable note entries.',
  'market-listing': 'A marketplace listing with product photo, price, condition, seller, description, and actions.',
  'property-listing': 'A property listing with a full gallery, price and location facts, amenities, and history.',
  'letter-dispatch': 'A formatted personal or official letter with sender, recipient, subject, body, and attachment.',
  'medical-record': 'A fictional clinical record with patient summary, documentary media, vitals, and notes.',
  'court-transcript': 'A readable court transcript with case metadata, ordered speakers, objections, and exhibits.',
  'codex-entry': 'A reference article for a person, place, object, or concept with facts and related entries.',
  'diary-app': 'A private diary with an owner, title, and multiple dated entries kept as separate pages.',
  'mission-board': 'A mission or task board with owner, deadline, status, checklist items, and notes.',
  'cctv-evidence': 'A multi-feed surveillance evidence board with fixed-camera frames and case notes.',
  'instagram-profile': 'A complete Instagram profile with avatar, bio, metrics, posts, comments, and tagged media.',
  'twitter-profile': 'A complete X profile with avatar, banner, metrics, timeline posts, and media grid.',
  'instagram-stories': 'An ordered set of vertical social stories with reusable avatars, media, captions, and times.',
}

export const NARRATIVE_UTILITY_OVERVIEWS: Readonly<Record<string, string>> = {
  'Character Phone': 'Builds a story-aware character phone with apps, messages, records, and contextual media.',
  'Dramatic Cutaway': 'Shows a cinematic parallel beat or interruption without losing the main scene viewpoint.',
  'Plot Sparks': 'Offers optional complications and pressure points the story can naturally act on next.',
  'Scene Shift': 'Summarizes the present scene, active direction, tension, and immediate story anchors.',
  'Parallel Scene': 'Tracks meaningful off-screen developments in a horizontally browsable current.',
  'Cast Introduction': 'Introduces a newly relevant recurring character with scene-safe identity information.',
  'Backstage Secrets': 'Separates what each character knows, suspects, misunderstands, or is hiding.',
  'Setting the Scene': 'Adds concrete, viewpoint-safe details that make the current place and culture feel lived in.',
  'Off-Stage': 'Reveals relevant events happening just outside the focal scene without replacing it.',
  'Character Dossier': 'Maintains a structured dossier of a character’s established story facts and changes.',
  'Location File': 'Maintains a structured record of a location, its features, history, and current state.',
  'In Another Life': 'Explores a clearly labeled hypothetical branch without rewriting canonical events.',
  'Archive Entry': 'Coordinates the enabled Narrative Utilities into one consistent archive payload.',
}

export const SETTING_HELP: Readonly<Record<string, string>> = {
  'Automatic Surface Injection': 'When on, Relay inserts the shared Surface grammar plus every enabled Utility into the Story Model prompt. Turn it off when you place a Relay macro manually in a preset.',
  'Renderer': 'Chooses who turns authored Surface markup into the visible interface. Relay Rendered is the default; Regex and Hybrid are compatibility choices.',
  'Default Presentation': 'Controls whether new Surfaces open inline or behind a compact launcher. It does not rewrite stored Surface content.',
  'Color Mode': 'Switches approved Surface accents between platform-realistic colors and your current Lumiverse primary theme.',
  'Injection Position': 'Chooses where Relay places its model instructions in the assembled prompt. Later positions are closer to the newest user message.',
  'Parser Connection': 'The Lumiverse text connection used for Relay planning and parsing. Follow Native Parser mirrors the host selection instead.',
  'ImageGen Connection': 'The Lumiverse Image Generation connection Relay uses. Leaving it on default follows Lumiverse’s active/default image connection.',
  'Model / Checkpoint': 'Optional checkpoint override. Leave empty to use the selected ImageGen connection’s configured model.',
  'Sampler': 'The provider sampling algorithm. Use the connection default unless you know the selected checkpoint prefers another sampler.',
  'Scheduler': 'Controls how denoising steps are distributed. Use the connection default when unsure.',
  'Steps': 'More steps can refine an image but take longer. The useful range depends on the provider and checkpoint.',
  'CFG / Guidance': 'Controls how strongly generation follows the prompt. Very high values can reduce natural detail or cause artifacts.',
  'Relay Stack': 'A reusable ordered set of provider LoRAs, weights, and optional trigger tags applied by Relay.',
  'Model Weight': 'How strongly this LoRA affects the diffusion model. Start near the model author’s recommended value.',
  'CLIP Weight': 'How strongly this LoRA affects text conditioning. Leave at the model weight unless the LoRA documents a different value.',
  'Auto Generate': 'When off, Relay may prepare requests but cannot spend an image-generation job automatically. This is enforced by the backend.',
  'Concurrent Image Jobs': 'Maximum Relay image jobs allowed at once. Lower values use less GPU memory and reduce provider contention.',
  'Appearance Memory Strength': 'Controls how strongly Relay carries established visual identity into new image prompts.',
  'Appearance Sidecar Source': 'Choose the shared global Appearance Sidecar or an Illustrator-specific override.',
  'Illustration Count': 'Choose an exact number or an inclusive range for model-placed illustrations.',
  'Aspect Policy': 'Reserves and generates each illustration at the selected ratio. Adaptive lets Relay choose from scene composition.',
  'Prompt Profile': 'Selects a curated image-prompt style and framing profile before provider submission.',
  'Image Alignment': 'Positions completed prose illustrations within the message column.',
  'Image Size': 'Sets the displayed width of completed prose illustrations without changing the generated source file.',
  'Candidate Count per Illustration': 'Generates multiple choices for review. Higher counts cost more time and provider work.',
  'Frequency': 'Controls which eligible assistant messages may receive prose illustrations.',
  'Every N Eligible Messages': 'When Frequency uses Every N, this sets the interval. Skipped or ineligible messages do not count.',
  'Minimum Message Length': 'Messages shorter than this are not considered for automatic illustration planning.',
  'Surface ID': 'A unique stable identifier for this exact Surface preset, for example relationship-map.',
  'Base Surface ID': 'The shared semantic identity for presets that render the same Surface contract.',
  'Bracket Surface Root': 'The model-facing bracket root that identifies this Surface. Enter only the root name; Relay supplies [root] and [/root]. Legacy XML shells remain compatibility input only.',
  'Image Target': 'The Relay route used by image requests owned by this Surface. It must match the runtime contract.',
  'Surface Utility / Model Instructions': 'The exact instructions Relay injects into the Story Model when this custom Surface is enabled. Explain when to author it, its required fields, media ownership, and the complete output format.',
  'Canonical Validation Fixture': 'A complete internal compatibility fixture used for validation and preview. Relay converts it to bracket-native model instructions while preserving image_request as nested XML.',
  'Utility Category': 'Where this custom Surface appears in the Surface Library. The category organizes its toggle; it does not change rendering, validation, or prompt behavior.',
  'Advanced namespaced CSS': 'Optional presentation-only CSS for this Surface. Keep every selector scoped to its wrapper; scripts, event handlers, imports, and JavaScript URLs are rejected.',
  'Inject Surface Utility': 'Includes this custom Surface’s model instructions when its module is enabled.',
  'Narrative Presentation': 'Chooses the approved Narrative launcher style installed by Relay. It does not change Utility content.',
  'Interface Theme': 'Changes only the Relay settings panel appearance; generated Surface designs keep their approved styling.',
  'Debug logging': 'Adds detailed local diagnostics for troubleshooting. It can be noisy and should normally stay off.',
}

export function settingHelp(label: string, fallback = ''): string {
  return SETTING_HELP[label] || fallback || `${label} controls this Relay setting. Change it only when you want to override the current default.`
}
